name: supplyme_client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  vector_graphics: ^1.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.svg
    - assets/images/logo.svg.vec
    - assets/images/logonotext.svg
    - assets/images/logonotext.svg.vec

fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans.ttf
        - asset: assets/fonts/PlusJakartaSansItalic.ttf
          style: italic
